Assign Address-IP6 field to netmask instead of address
The Address-IP6 field combines the address and netmask into one line,
meaning it only makes sense in the netmask field.

Fixes an error rather not dissimilar to the following:

  Error: an inet prefix is expected rather than "<foo>/64/128"

Signed-off-by: Jeremy Visser <jeremy@visser.name>
Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>