Add liboath version check
Versions prior to 1.12.0 are missing oath_base32_decode(), resulting in an
error:

      CC     libopenconnect_la-library.lo
    library.c: In function 'set_oath_mode':
    library.c:475:3: error: implicit declaration of function 'oath_base32_decode' [-Werror=implicit-function-declaration]
    library.c:475:3: warning: nested extern declaration of 'oath_base32_decode' [-Wnested-externs]

Signed-off-by: Kevin Cernekee <cernekee@gmail.com>
Signed-off-by: David Woodhouse <David.Woodhouse@intel.com>